server:
  port: 8083
 
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: SALON-SERVICE
        uri: lb://SALON-SERVICE
        predicates:
        - Path=/api/salon/**
        
       
    
            
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/api/** 


            
            
              
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
  server:
    peer-node-read-timeout-ms: '10000'