#server:
#  port: 8081
#spring:
#  application:
#    name: SALON-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql://localhost:3306/testuserdb?serverTimezone=UTC
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL55Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#       format_sql: true
#    show-sql: true
#
#
#bezkoder:
#  app:
#    jwtExpirationMs: '86400000'
#    jwtSecret: bezKoderSecretKey
#    
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true